Initial tests for override status assertion
wiley/healthcat pull request #54
Opened 2021-08-17 23:08 UTC by anlsergio

2021-08-24 19:45 UTC, dgeorgievski commented
Hi @anlsergio , I can take this over if you don't have the time, but first please provide the description about the intent.

2021-08-24 22:49 UTC, anlsergio commented
Hey @dgeorgievski  

I actually got back to it this morning and I've made a lot of progress in my local env, so I'll probably mark this PR as ready for review by the end of the week.

I don't know if that's the best approach but I usually like to turn my WIP branch as a draft PR and then add the proper description as the code evolves until it's finally ready for review.

Unless you guys are in a hurry about this one, I'll be able to wrap this up in a few days, otherwise, let me know and I'll commit/push my local changes to the remote so you can take it from there.

2021-08-24 23:00 UTC, anlsergio commented
By the way, don't bother to start reviewing it yet, because it's lacking refactoring, fixing typos and even the HTTP method in the test is wrong, don't waste your time yet :)

It's still a WIP.

2021-08-30 18:04 UTC, dgeorgievski commented
Reviewing

2021-08-31 19:15 UTC, dgeorgievski requested changes
The status management works as expected, but I'd refine the approach a bit to reflect the fact that a new field tracking maintenance status was added, that we need to see the status change in the logs as info message, and that some input validation is required.

2021-08-31 19:19 UTC, dgeorgievski commented on checker/checker.go
> +	c.slogger.Errorf("Invalid status setting of %s", newStatus)
Example of current error message. The exception stack is not needed, only an info about incorrect parameter
```
healthcat-chc-6d884c48b9-rztpc chc {"level":"error","ts":1630434622.137632,"caller":"checker/checker.go:167","msg":"Invalid status setting of dimi","stacktrace":"wiley.com/healthcat/checker.(*Checker).ArbitrarilySetClusterHealthState\n\t/go/src/github.com/wiley/healthcat/checker/checker.go:167\nwiley.com/healthcat/server.router.func2\n\t/go/src/github.com/wiley/healthcat/server/server.go:102\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/go-chi/chi.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nwiley.com/healthcat/logger.RecoveryWithZap.func1.1\n\t/go/src/github.com/wiley/healthcat/logger/zap.go:112\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nwiley.com/healthcat/logger.Chczap.func1.1\n\t/go/src/github.com/wiley/healthcat/logger/zap.go:38\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/go-chi/chi.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925"}
```

2021-08-31 23:35 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) ArbitrarilySetClusterHealthState(newStatus string) {
It makes sense, but TBH, in this case, I see much more value in turning the new parameter as a boolean instead, which will make even more sense and it would make the field validation much less verbose.

2021-08-31 23:36 UTC, anlsergio commented on server/server.go
> +		var s struct { NewStatus string }
Why not validating a boolean instead then? :)

2021-08-31 23:58 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
You are absolutely right! I just trying to follow the same pattern as its companion functions which adopt the adjective form, such as `Healthy` and `Ready` but none of them look like method names, so I'll take the opportunity to refactor them all.

2021-09-01 01:15 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
Actually, I'll avoid messing with code that is not directly tied to this PR scope and I'll have that as a note for another PR designed for that.

With that being said, I only refactored the `InMaintenance` function as of now.

2021-09-01 01:18 UTC, anlsergio commented on server/server.go
> +		var s struct { NewStatus string }
Resolved at https://github.com/wiley/healthcat/pull/54/commits/cf8421c8c50f9655bda6d4cf55d3b0cec262db29 where the field is now being treated as boolean

2021-09-01 01:24 UTC, anlsergio commented on checker/checker.go
> +	c.slogger.Errorf("Invalid status setting of %s", newStatus)
Now that the field is being treated as boolean the validation is done during JSON Unmarshall and if the provided value doesn't match a boolean, the response is going to return a `400 Bad Request status code` back to the client:

/tmp/Spectacle.sBtbBN/Screenshot_20210831_222129.png

2021-09-01 01:31 UTC, anlsergio commented
PR description and title updated

2021-09-01 07:51 UTC, axykon commented
Just a thought. The `healthy` and `inMaintenance` fields are mutually-exclusive, right? So, there are no situations when a cluster might be in maintenance and healthy at the same time. What do you think about a single string-typed attribute, say, `status`, which would accept values from the list of `healthy`, `InMaintenance` and `Failed`?

2021-09-01 13:17 UTC, anlsergio commented
> Just a thought. The `healthy` and `inMaintenance` fields are mutually-exclusive, right? So, there are no situations when a cluster might be in maintenance and healthy at the same time. What do you think about a single string-typed attribute, say, `status`, which would accept values from the list of `healthy`, `InMaintenance` and `Failed`?

That looks reasonable indeed if there's no foreseen use case for explicitly making use of both fields in a way that they make sense to coexist.

I'll work on that, thanks for the suggestions guys!

2021-09-01 14:00 UTC, dgeorgievski commented
> Just a thought. The `healthy` and `inMaintenance` fields are mutually-exclusive, right? So, there are no situations when a cluster might be in maintenance and healthy at the same time. What do you think about a single string-typed attribute, say, `status`, which would accept values from the list of `healthy`, `InMaintenance` and `Failed`?

This was the original idea, but I have to say @anlsergio  proposal made me re-think the original approach. In the end the simpler solution always wins.

2021-09-02 08:56 UTC, axykon commented on checker/checker.go
> +func (c *Checker) GetMaintenanceStatus() bool {
Was this method name made inconsistent with its counterpart `SetMaintenanceMode` intentionally? Getters/setters usually have the same base name. Also, for getters it is encouraged to not prefix them with the "Get" prefix - see https://golang.org/doc/effective_go#Getters.

2021-09-02 10:36 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) GetMaintenanceStatus() bool {
Actually yes, because one method is telling me that its purpose is to set the maintenance mode while the other is telling me what the current status of the maintenance mode is. 

But now that I look at the bigger picture, I think you are right, since they work as Getters and Setters it's better to make them consistent about the naming convention.

Thanks for the hint about the proper way of naming a Getter method by the way.

I'd even say that since it is currently returning a boolean at this point, the question it's trying to answer is whether the Maintenance Mode is `true` or `false`, nothing else. Then it should be changed to something like `IsInMaintenanceMode()` instead I think. 

However, considering I'm going to refactor the whole thing in order for the cluster status property to answer that question for us, then most probably this method will be gone, but it's good that you pointed this out, so I'll try to remember that for a similar use case!

2021-09-02 11:32 UTC, axykon commented on checker/checker.go
> +func (c *Checker) GetMaintenanceStatus() bool {
Actually, I like the previous version `InMaintenance` more :). It reads very clearly together with `if` statement: `if sr.InMaintenance()`. On the other hand `if sr.GetMaintenanceStatus()` looks confusing IMO.

2021-09-02 11:40 UTC, axykon commented
> > Just a thought. The `healthy` and `inMaintenance` fields are mutually-exclusive, right? So, there are no situations when a cluster might be in maintenance and healthy at the same time. What do you think about a single string-typed attribute, say, `status`, which would accept values from the list of `healthy`, `InMaintenance` and `Failed`?
> 
> This was the original idea, but I have to say @anlsergio proposal made me re-think the original approach. In the end the simpler solution always wins.

We may internally use two boolean fields, but return the single status string in the http response, thus making our response simpler than with two separate booleans: a client would need to check only three states instead of possible four - produced by different combinations of two boolean values. But I am OK with both options,  I'm just thinking aloud

2021-09-02 12:46 UTC, axykon commented on checker/checker.go
> +		c.healthy = true
I think we need to re-calculate the healthy state instead of setting it to `true` unconditionally.

2021-09-02 12:49 UTC, axykon commented on checker/checker.go
> +		c.slogger.Infof("The 'Maintenance Mode' has been turned off. The cluster is set back to its original state")
While being in maintenance, the state of the cluster may change - I think it is enough to log that the maintenance mode was turned off.

2021-09-02 13:05 UTC, axykon commented on server/server.go
> +		if err != nil {
I think it would be helpful if we log the error here

2021-09-02 13:19 UTC, axykon commented on server/server_test.go
> +			} else if responseGot != responseWant {
I think the two conditions are not dependent on each other,  so they can be checked separately, without `else`

2021-09-09 18:13 UTC, anlsergio commented
For the heads up, I've been very busy the past few days but I'll be glad to continue working on this during the weekend.

2021-09-12 12:22 UTC, anlsergio commented
Hello everybody, just getting back to the "set maintenance mode/status" feature. Now that I'm coding it I don't see any reason why one would arbitrarily set the status to fail if there's a maintenance mode status available for maintenance purposes.

Also, it feels like allowing one to set the cluster status to Ok/Healthy doesn't feel right either, instead, disabling the maintenance mode should cause the cluster to start recalculating its own health status.

While I still agree that the status endpoint should be simpler and return the current status of the cluster being either `Ok/Healthy`, `Maintenance`, or `Fail`.

I'll code and submit my proposal having this in mind then let me know what do you guys think but feel free to share your thoughts in the meanwhile.

2021-09-12 22:01 UTC, anlsergio commented
PR description and title updated (I wrapped this up for today and left it in a working state but I'll review it for cleaning purposes ASAP before asking for a new review)

2021-09-14 09:54 UTC, axykon commented on checker/checker.go
> +		c.healthy = false
As we call `c.updateStatus()` in both cases, wouldn't it be better to move the `c.healthy = ...` into that method for consistency?

2021-09-14 10:12 UTC, axykon commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
I think this should be called just `MaintenanceMode()` to match the corresponding setter - `SetMaintenanceMode()`. Also, in Go it is uncommon to prefix getters with the "Get" prefix: https://golang.org/doc/effective_go#Getters

2021-09-14 11:21 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
>Also, in Go it is uncommon to prefix getters with the "Get" prefix: https://golang.org/doc/effective_go#Getters

Actually, as we discussed about the Getter naming convention and how the method should be read along with the receiver (e.g. `sr.InMaintenance()`) I fixed it at: https://github.com/wiley/healthcat/pull/54/commits/e721daa928c9dc05b03fdcfcf7907aa6f338deb9

But if you think it would be better to rename it as just `MaintenanceMode` in order to match its counterpart Setter method, it looks good to me too.

2021-09-14 11:23 UTC, axykon commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
Or we can go the other way and rename the setter: `SetInMaintenance()`

2021-09-15 10:55 UTC, anlsergio commented on checker/checker.go
> +		c.healthy = false
Agreed!

2021-09-15 11:09 UTC, anlsergio commented
PR description updated in order to meet the new field name in the JSON payload.

2021-09-15 11:14 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) InMaintenance() bool {
I've decided to go for the `MaintenanceMode()` approach :)

2021-09-15 15:39 UTC, dgeorgievski approved these changes
👍

2021-09-15 15:59 UTC, axykon approved these changes
LGTM!

2021-09-15 17:56 UTC, merged