Dynamic service update
wiley/healthcat pull request #55
Opened 2021-08-18 13:37 UTC by axykon

Originally, if a service being tracked by healthcat was updated, the healthcat removed and then re-added the service to an internal service registry using a client-side interface where removal and addition of the same service were not synchronized to each other. So, theoretically, the `Add` method could take effect before `Delete` finished . The new implementation adds an client-interface method `Update` which updates the service in a well-ordered way eliminating race conditions.

Closes #42

2021-09-01 15:24 UTC, dgeorgievski submitted a review, later dismissed
👍 works as expected

Initial state
```
 k get svc
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
nginx-1    ClusterIP   10.96.189.145   <none>        8080/TCP   3m28s
nginx-10   ClusterIP   10.96.48.240    <none>        80/TCP     3m25s
nginx-2    ClusterIP   10.96.88.108    <none>        80/TCP     3m27s
nginx-3    ClusterIP   10.96.186.249   <none>        80/TCP     3m27s
nginx-4    ClusterIP   10.96.103.125   <none>        80/TCP     3m27s
nginx-5    ClusterIP   10.96.36.112    <none>        80/TCP     3m27s
nginx-6    ClusterIP   10.96.176.42    <none>        80/TCP     3m26s
nginx-7    ClusterIP   10.96.14.49     <none>        80/TCP     3m26s
nginx-8    ClusterIP   10.96.164.92    <none>        80/TCP     3m26s
nginx-9    ClusterIP   10.96.103.12    <none>        80/TCP     3m25s
```

Log entry for nginx-1 from healthcat
```
healthcat-chc-7798b7f67c-xh97f chc 2021-09-01T15:18:27.909Z	INFO	checker/checker.go:286	Report from http://nginx-1.test:8080/healthz: s:5, h:true, err:<nil>
```

Change the svc port of nginx-1  to 9080
```
 k get svc
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
nginx-1    ClusterIP   10.96.189.145   <none>        9080/TCP   5m21s
nginx-10   ClusterIP   10.96.48.240    <none>        80/TCP     5m18s
nginx-2    ClusterIP   10.96.88.108    <none>        80/TCP     5m20s
nginx-3    ClusterIP   10.96.186.249   <none>        80/TCP     5m20s
nginx-4    ClusterIP   10.96.103.125   <none>        80/TCP     5m20s
nginx-5    ClusterIP   10.96.36.112    <none>        80/TCP     5m20s
nginx-6    ClusterIP   10.96.176.42    <none>        80/TCP     5m19s
nginx-7    ClusterIP   10.96.14.49     <none>        80/TCP     5m19s
nginx-8    ClusterIP   10.96.164.92    <none>        80/TCP     5m19s
nginx-9    ClusterIP   10.96.103.12    <none>        80/TCP     5m18s
```

And the change is automatically picked up by healthcat
```
healthcat-chc-7798b7f67c-xh97f chc 2021-09-01T15:19:42.718Z	INFO	checker/checker.go:286	Report from http://nginx-1.test:9080/healthz: s:1, h:true, err:<nil>
```

2021-09-01 15:25 UTC, dgeorgievski commented
@axykon , please squash some of the commits and comments.

2021-09-01 17:14 UTC, anlsergio reviewed
I left a review, more like a suggestion for cleanness :)

2021-09-01 17:14 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) Update(name string, url string) {
I'd suggest adopting a more descriptive function name, such as `UpdateService`, or even better if you will `UpdateAlreadyRegisteredService` so that the function name is auto-explanatory and not even comments are needed anymore, which makes the code a lot less cluttered in the long run.

2021-09-01 18:44 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) Update(name string, url string) {
Agreed!

2021-09-02 09:07 UTC, axykon commented on checker/checker.go
> +func (c *Checker) Update(name string, url string) {
Good point about names! Unfortunately, I wasn't consistent when gave names to things: services are sometimes are referred to as services and sometimes as targets(. BTW, which name do you guys prefer more?

2021-09-02 10:47 UTC, anlsergio commented on checker/checker.go
> +func (c *Checker) Update(name string, url string) {
I think `UpdateService` makes the purpose clear enough.

2021-09-15 20:04 UTC, dgeorgievski requested changes
Please see my comments related to the latest commit - a rebase from master. A couple of simple changes we could address with this PR
https://github.com/wiley/healthcat/commit/072199e2558d77fdce3ebe93a92fe9702423b049#comments

2021-09-17 15:53 UTC, dgeorgievski approved these changes
👍

2021-09-21 09:48 UTC, anlsergio approved these changes

2021-09-21 09:56 UTC, merged